name: Show runs status in Readme.md on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  lint-backend:
    uses: ./.github/workflows/get-runs-status.yaml
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
